---
abstract: ~
author:
  - ', the above named PROJECT FOUNDER and CONTRIBUTORS.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: eupl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Zaaksysteem
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Any::Moose: 0
  AppConfig: 0
  Archive::Zip: 0
  Catalyst::Action::REST: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::LDAP: 0
  Catalyst::Controller::SOAP: 0
  Catalyst::Model::Adaptor: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::ClamAV: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::Params::Profile: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::Runtime: 5.80007
  Catalyst::View::Download: 0
  Catalyst::View::Email: 0
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  ClamAV::Client: 0
  Clone: 0
  Config::General: 0
  DBIx::Class: 0.08195
  DBIx::Class::Cursor::Cached: 0
  DBIx::Class::Helper::ResultSet::SetOperations: 0
  DBIx::Class::Schema::Loader: 0
  DBIx::Class::TimeStamp: 0
  DBIx::ContextualFetch: 0
  DBIx::DBSchema: 0
  DBIx::SearchBuilder: 0
  Data::FormValidator: 0
  Data::Serializer: 0.59
  Data::UUID: 0
  DateTime: 0
  DateTime::Format::Pg: 0
  Digest::MD5: 0
  Digest::MD5::File: 0
  FCGI::ProcManager: 0
  FCGI::ProcManager::MaxRequests: 0
  File::Copy: 0
  Geo::Coder::Google: 0
  GnuPG::Interface: 0
  HTML::TagFilter: 0
  Hash::Merge::Simple: 0
  Image::Magick: 0
  JSON: 0
  Log::Dispatch: 0
  Log::Log4perl: 0
  MIME::Lite: 0
  MIME::Tools: 0
  MIME::Types: 0
  Module::Pluggable::Fast: 0
  Moose: 0
  MooseX::Aliases: 0
  MooseX::Clone: 0
  MooseX::Emulate::Class::Accessor::Fast: 0
  MooseX::Getopt: 0
  MooseX::MethodAttributes: 0
  MooseX::Params::Validate: 0
  MooseX::Role::WithOverloading: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::Storage: 0
  MooseX::Traits::Pluggable: 0
  MooseX::Types: 0
  MooseX::Types::Common: 0
  Net::LDAP: 0
  Net::LDAP::Server: 0
  OpenOffice::OODoc: 0
  Params::Profile: 0
  Text::CSV: 0
  UUID: 0
  Unicode::String: 0
  XML::Dumper: 0
  XML::Parser: 0
  XML::Tidy: 0
  XML::Twig: 0
  parent: 0
version: 2.4.3
