=head1 NAME

Zaaksysteem - Een complete oplossing om de dienstverlening te verbeteren

=head1 SYNOPSIS

Maak gebruik van L<http://wiki.zaaksysteem.nl/> voor de complete documentatie
van het zaaksysteem.

=head1 DESCRIPTION

Het zaaksysteem.nl is een complete oplossing (all-in-one) voor gemeenten om de
dienstverlening te verbeteren. Het biedt functionaliteit voor burgers en
medewerkers om zaken af te handelen vanuit huis, in het KCC of in de
backoffice.

Zaaksysteem.nl is het enige zaaksysteem in Nederland dat volledig is
ontwikkeld in en als open source software. Dit is gedaan onder andere gedaan
om zoveel mogelijk te voldoen aan het landelijke beleid en om gemeenten een
gunstig tarief te bieden.

=head1 INSTALLATIE

Er is kennis van linux omgevingen en een gedegen kennis van de programmeertaal
perl  vereist om aan de hand van deze handleiding zaaksysteem succesvol te
installeren. Hoewel alle stappen in deze handleiding door ons team nauwkeurig
zijn vastgesteld, kan de exacte methode om zaaksysteem.nl te installeren
afhangen van verschillende factoren: de gebruikte versie van de linux
distributie, de geinstalleerde perl modules etc.

Mocht u onderdelen tegenkomen die verbetert kunnen worden, aarzel dit niet op
te nemen in onze wiki.

=head2 SYSTEEMVEREISTEN

=over 4

=item Degelijke linux distributie

Onze voorkeur gaat uit naar Ubuntu Server, maar elk debian of redhat gebaseerd
OS moet voldoen.

=item Minimaal 1 GB Ram

Zaaksysteem, tomcat en openoffice samen.

=item Diskspace minimaal 1,5 GB

Zaaksysteem.nl met alle relevante packages neemt ongeveer 1 GB in gebruik.
Extra ruimte is aanbevolen voor het uploaden van documenten

=back

=head2 Componenten

Om alle functionaliteiten van Zaaksysteem te kunnen gebruiken dienen de
volgende componenten op het systeem geinstalleerd te zijn

=over 4

=item libreoffice (headless)

=item clamav virusscanner (clamd)

=item tomcat (6 of 7)

=item postgresql

=item openldap

=item nginx

=back

=head2 Zaaksysteem installatie

Met de volgende commando's kunt u zaaksysteem installeren.

=head3 Voorbereiden package

 tar xfvz Zaaksysteem-VERSIE.tar.gz
 cd Zaaksysteem-VERSIE

=head3 Configureren cpan

De installatie van zaaksysteem maakt gebruik van cpan om de overige modules te
installeren. Het kan aan te raden zijn om cpan eerst te configureren, om te
voorkomen dat het bij elke requirement vraagt of deze geinstalleerd dient te
worden

 # cpan

 cpan shell -- CPAN exploration and modules installation (v1.9402)
 Enter 'h' for help.

 cpan[1]> o conf prerequisites_policy follow
    prerequisites_policy [follow]
    Please use 'o conf commit' to make the config permanent!
 cpan[2]> o conf commit
 cpan[2]> quit

=head3 Installeren zaaksysteem

Het zaaksysteem wordt geinstalleerd met de volgende commando's

 perl Makefile.PL

Antwoord y op de vraag of de vereiste packages geinstalleerd dienen te worden

 make
 make install

=head1 CONFIGURATIE

=head2 Configuratie verschillende componenten

=over 4

=item openoffice.org

Start openoffice.org als headless server om tegenaan te babbelen.

 soffice --headless --accept="socket,host=127.0.0.1,port=8100;urp;" \
  --nologo --nodefault --nofirststartwizard

=item tomcat7

Om ervoor te zorgen dat niet elke leecher op het interweb gebruik maakt van
onze document converter, zorgen we ervoor dat tomcat enkel luistert op
localhost. Zoek de juiste connector, en voeg de address="127.0.0.1" attribute
toe.

 # vim /etc/etc/tomcat7/server.xml

    <Connector port="8080" protocol="HTTP/1.1"
               address="127.0.0.1"
               connectionTimeout="20000" 
               URIEncoding="UTF-8"
               redirectPort="8443" />

=back

=head2 Configuratie PostgreSQL + OpenLDAP

=head3 PostgreSQL

Zaaksysteem maakt gebruik van 2 databases, een server voor het opslaan van het
gegevensmagazijn en een database voor het zaaksysteem zelf.

=over 4

=item create database user

Maak een databaseusers aan als user postgres

 sudo -u postgres createuser zaaksysteem

=item create databases

Maak beide databases aan

 psql template1
 > create database zaaksysteem_gegevens with owner zaaksysteem;
 > create database zaaksysteem_beheer with owner zaaksysteem;

=item import database

Importeer beide kale databases

 cat /usr/share/perl5/Zaaksysteem/db/gegevens.sql | psql zaaksysteem_gegevens
 cat /usr/share/perl5/Zaaksysteem/db/beheer.sql | psql zaaksysteem_beheer

=item ADVANCED

Zorg voor de juiste access permissions in /etc/postgresql/pg_hba.conf

=back

=head3 OpenLDAP

Configureerd slapd

 dpkg-reconfigure slapd

DNS Domeinnaam: zaaksysteem.nl

 ldapadd -W -x -D "cn=admin,dc=zaaksysteem,dc=nl" -f zaaksysteem.ldif

Authorisatie per container

 olcAccess: {3}to dn.base="o=zaaksysteem,dc=zaaksysteem,dc=nl" by
 dn="cn=admin,ou=Management,o=zaaksysteem,dc=zaaksysteem,dc=nl" write by *
 read

=head3 NGINX

Na installatie nginx, plaats het voorbeeld nginx script in
/etc/nginx/sites-available

 cp /usr/share/perl5/Zaaksysteem/drafts/nginx-zaaksysteem.conf \
  /etc/nginx
 cp /usr/share/perl5/Zaaksysteem/drafts/nginx-zaaksysteem-virtualhost.conf \
  /etc/nginx/sites-available/default

Vergeet de fastcgi_params niet, ivm met catalyst zit er een kleine wijziging
in PATH_INFO waardoor deze lichtelijk gewijzigd is.

 cp /usr/share/perl5/Zaaksysteem/drafts/nginx-fastcgi_params /etc/nginx/

Met SSL

 mkdir /etc/nginx/ssl
 cmod 700 /etc/nginx/ssl

Plaats uw ssl certificaten in /etc/nginx/ssl


=head2 Configuratie Zaaksysteem.nl

=head3 Config

Kopieer de zaaksysteem dist config naar /etc/zaaksysteem.

 sudo mkdir /etc/zaaksysteem
 cp /usr/share/perl5/Zaaksysteem/zaaksysteem.conf.dist \
  /etc/zaaksysteem/zaaksysteem.conf

En edit accordingly

=head3 StartUP

Wanneer het gebruikte OS gebruik maakt van UPSTART, kopieer dan de upstart
jobs naar /etc/init.

 cp /usr/share/perl5/Zaaksysteem/drafts/upstart-openoffice-headless.conf \
  /etc/init
 cp /usr/share/perl5/Zaaksysteem/drafts/upstart-zaaksysteem.conf \
  /etc/init

Vergeet niet de benodigde users aan te maken

 adduser zaaksysteem
 adduser openoffice

=head3 Data directory

Maak de juiste data directory aan, wij maken gebruik van /srv:

mkdir -p /srv/zaaksysteem/data/localhost
mkdir /srv/zaaksysteem/data/localhost/{documents,,drops,filestore,kenmerken}
mkdir /srv/zaaksysteem/data/localhost/{thumbnails,tmp,zaaktype}
mkdir /srv/zaaksysteem/data/localhost/tmp/store

=head3 Security

Zorg dat de volgende paden de juiste permissie ontvangen

 chmod -R 750 /srv/zaaksysteem/data/localhost
 chmod 640 /etc/zaaksysteem/zaaksysteem.conf
 chown :zaaksysteem /etc/zaaksysteem/zaaksysteem.conf
 chown -R zaaksysteem:zaaksysteem /srv/zaaksysteem/data/localhost

=head1 START ZAAKSYSTEEM

=head2 Start bijbehorende componenten

 start tomcat7
 start openoffice-headless
 start clamav-daemon
 start clamav-freshclam

=head2 Start zaaksysteem

Zaaksysteem maakt gebruik van FCGI::ProcManager, wat betekent dat er een
proces met 5 children wordt opgestart. Om memory leaks te voorkomen pakt elk
child maximaal 100 requests.

De optie respawn is gezet, wat ervoor zorgt dat zaaksysteem opnieuw opstart
wanneer op de een of andere manier de processmanager crashed.

 start zaaksysteem
 start nginx

=head1 INLOGGEN

De standaard gebruikersnaam voor de admin gebruiker is "admin" met wachtwoord
"admin"

Enjoy!

=head1 SUPPORT

Op de community editie wordt enkel support geleverd via de wiki. Voor
professionele support kunt u contact opnemen met Mintlab L<http://www.mintlab.nl>

=head1 SEE ALSO

Maak gebruik van L<http://wiki.zaaksysteem.nl/> voor de complete documentatie
van het zaaksysteem.

=head1 PROJECT FOUNDER

Mintlab B.V. <info@mintlab.nl>

=head1 CONTRIBUTORS

Arne de Boer

Nicolette Koedam

Marjolein Bryant

Peter Moen

Michiel Ootjers

Jonas Paarlberg

Jan-Willem Buitenhuis

Martin Kip

Gemeente Bussum

=head1 COPYRIGHT

Copyright (c) 2009, the above named PROJECT FOUNDER and CONTRIBUTORS.

=head1 LICENSE

The contents of this file and the complete zaaksysteem.nl distribution
are subject to the EUPL, Version 1.1 or - as soon they will be approved by the
European Commission - subsequent versions of the EUPL (the "Licence"); you may
not use this file except in compliance with the License. You may obtain a copy
of the License at
L<http://joinup.ec.europa.eu/software/page/eupl>

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
the specific language governing rights and limitations under the License.

=cut
