package Zaaksysteem::SchemaGM::NatuurlijkPersoon;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("InflateColumn::DateTime", "TimeStamp", "Core");
__PACKAGE__->table("natuurlijk_persoon");
__PACKAGE__->add_columns(
  "id",
  {
    data_type => "integer",
    default_value => "nextval('natuurlijk_persoon_id_seq'::regclass)",
    is_nullable => 0,
    size => 4,
  },
  "burgerservicenummer",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 9,
  },
  "a_nummer",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 10,
  },
  "voorletters",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 10,
  },
  "voornamen",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 200,
  },
  "geslachtsnaam",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 200,
  },
  "voorvoegsel",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 50,
  },
  "geslachtsaanduiding",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 3,
  },
  "nationaliteitscode1",
  {
    data_type => "smallint",
    default_value => undef,
    is_nullable => 1,
    size => 2,
  },
  "nationaliteitscode2",
  {
    data_type => "smallint",
    default_value => undef,
    is_nullable => 1,
    size => 2,
  },
  "nationaliteitscode3",
  {
    data_type => "smallint",
    default_value => undef,
    is_nullable => 1,
    size => 2,
  },
  "geboortegemeente",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 75,
  },
  "geboorteplaats",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 75,
  },
  "geboortegemeente_omschrijving",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 150,
  },
  "geboorteregio",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 150,
  },
  "geboorteland",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 75,
  },
  "geboortedatum",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "aanhef_aanschrijving",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 10,
  },
  "voorletters_aanschrijving",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 20,
  },
  "voornamen_aanschrijving",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 200,
  },
  "naam_aanschrijving",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 200,
  },
  "voorvoegsel_aanschrijving",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 50,
  },
  "burgerlijke_staat",
  {
    data_type => "character",
    default_value => undef,
    is_nullable => 1,
    size => 1,
  },
  "indicatie_gezag",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 2,
  },
  "indicatie_curatele",
  {
    data_type => "character",
    default_value => undef,
    is_nullable => 1,
    size => 1,
  },
  "indicatie_geheim",
  {
    data_type => "character",
    default_value => undef,
    is_nullable => 1,
    size => 1,
  },
  "aanduiding_verblijfsrecht",
  {
    data_type => "smallint",
    default_value => undef,
    is_nullable => 1,
    size => 2,
  },
  "datum_aanvang_verblijfsrecht",
  { data_type => "date", default_value => undef, is_nullable => 1, size => 4 },
  "datum_einde_verblijfsrecht",
  { data_type => "date", default_value => undef, is_nullable => 1, size => 4 },
  "aanduiding_soort_vreemdeling",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 10,
  },
  "land_vanwaar_ingeschreven",
  {
    data_type => "smallint",
    default_value => undef,
    is_nullable => 1,
    size => 2,
  },
  "land_waarnaar_vertrokken",
  {
    data_type => "smallint",
    default_value => undef,
    is_nullable => 1,
    size => 2,
  },
  "adres_buitenland1",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 35,
  },
  "adres_buitenland2",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 35,
  },
  "adres_buitenland3",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 35,
  },
  "nnp_ts",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 32,
  },
  "hash",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 32,
  },
  "import_datum",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "adres_id",
  { data_type => "integer", default_value => undef, is_nullable => 1, size => 4 },
  "email",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 32,
  },
  "telefoon",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 32,
  },
  "authenticated",
  { data_type => "boolean", default_value => undef, is_nullable => 1, size => 1 },
  "authenticatedby",
  {
    data_type => "text",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "deleted_on",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "verblijfsobject_id",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 16,
  },
  "datum_overlijden",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "aanduiding_naamgebruik",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 1,
  },
  "onderzoek_persoon",
  { data_type => "boolean", default_value => undef, is_nullable => 1, size => 1 },
  "onderzoek_persoon_ingang",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "onderzoek_persoon_einde",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "onderzoek_persoon_onjuist",
  { data_type => "boolean", default_value => undef, is_nullable => 1, size => 1 },
  "onderzoek_huwelijk",
  { data_type => "boolean", default_value => undef, is_nullable => 1, size => 1 },
  "onderzoek_huwelijk_ingang",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "onderzoek_huwelijk_einde",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "onderzoek_huwelijk_onjuist",
  { data_type => "boolean", default_value => undef, is_nullable => 1, size => 1 },
  "onderzoek_overlijden",
  { data_type => "boolean", default_value => undef, is_nullable => 1, size => 1 },
  "onderzoek_overlijden_ingang",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "onderzoek_overlijden_einde",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "onderzoek_overlijden_onjuist",
  { data_type => "boolean", default_value => undef, is_nullable => 1, size => 1 },
  "onderzoek_verblijfplaats",
  { data_type => "boolean", default_value => undef, is_nullable => 1, size => 1 },
  "onderzoek_verblijfplaats_ingang",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "onderzoek_verblijfplaats_einde",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "onderzoek_verblijfplaats_onjuist",
  { data_type => "boolean", default_value => undef, is_nullable => 1, size => 1 },
  "partner_a_nummer",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 50,
  },
  "partner_burgerservicenummer",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 50,
  },
  "partner_voorvoegsel",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 50,
  },
  "partner_geslachtsnaam",
  {
    data_type => "character varying",
    default_value => undef,
    is_nullable => 1,
    size => 50,
  },
  "datum_huwelijk",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
  "datum_huwelijk_ontbinding",
  {
    data_type => "timestamp without time zone",
    default_value => undef,
    is_nullable => 1,
    size => 8,
  },
);
__PACKAGE__->set_primary_key("id");
__PACKAGE__->add_unique_constraint("natuurlijk_persoon_pkey", ["id"]);
__PACKAGE__->belongs_to(
  "adres_id",
  "Zaaksysteem::SchemaGM::Adres",
  { id => "adres_id" },
);


# Created by DBIx::Class::Schema::Loader v0.04006 @ 2012-04-03 15:22:58
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:jMD9PSTSRahAajJygnElyw

__PACKAGE__->resultset_class('Zaaksysteem::SBUS::ResultSet::NatuurlijkPersoon');

__PACKAGE__->add_columns('import_datum',
    { %{ __PACKAGE__->column_info('import_datum') },
    set_on_create => 1,
});

__PACKAGE__->belongs_to(
  "verblijfsobject_id",
  "Zaaksysteem::SchemaGM::BagVerblijfsobject",
  { "identificatie" => "verblijfsobject_id" },
);

__PACKAGE__->load_components(
    "+Zaaksysteem::DB::Component::GmNatuurlijkPersoon",
    __PACKAGE__->load_components()
);

# You can replace this text with custom content, and it will be preserved on regeneration
1;
